import type { ArchetypeConfig, ArchetypeId } from '../types/ai'

export const ARCHETYPES: Record<ArchetypeId, ArchetypeConfig> = {
  nit: {
    id: 'nit',
    name: 'The Rock',
    description: 'Plays very few hands, only continues with premium holdings. Rarely bluffs.',
    vpip: 0.12,
    pfr: 0.08,
    af: 1.2,
    cbet: 0.40,
    foldToCbet: 0.65,
    bluffFreq: 0.04,
    threeBetFreq: 0.03,
    foldTo3bet: 0.75,
    btnMultiplier: 1.4,
    coMultiplier: 1.2,
    hjMultiplier: 1.1,
    betSizingMean: 0.55,
    betSizingStd: 0.08,
    timingMeanMs: 2800,
    timingStdMs: 900,
  },
  tag: {
    id: 'tag',
    name: 'The Pro',
    description: 'Tight-aggressive. Plays a solid, balanced range and bets for value and protection.',
    vpip: 0.22,
    pfr: 0.18,
    af: 3.0,
    cbet: 0.68,
    foldToCbet: 0.45,
    bluffFreq: 0.15,
    threeBetFreq: 0.07,
    foldTo3bet: 0.55,
    btnMultiplier: 1.6,
    coMultiplier: 1.4,
    hjMultiplier: 1.2,
    betSizingMean: 0.62,
    betSizingStd: 0.12,
    timingMeanMs: 1800,
    timingStdMs: 700,
  },
  lag: {
    id: 'lag',
    name: 'The Aggressor',
    description: 'Loose-aggressive. Plays many hands and applies constant pressure with bets and raises.',
    vpip: 0.35,
    pfr: 0.28,
    af: 3.5,
    cbet: 0.78,
    foldToCbet: 0.35,
    bluffFreq: 0.28,
    threeBetFreq: 0.12,
    foldTo3bet: 0.40,
    btnMultiplier: 1.8,
    coMultiplier: 1.5,
    hjMultiplier: 1.3,
    betSizingMean: 0.68,
    betSizingStd: 0.15,
    timingMeanMs: 1200,
    timingStdMs: 500,
  },
  callingstation: {
    id: 'callingstation',
    name: 'The Caller',
    description: 'Calls too much, rarely raises or folds. Great to value bet against, never bluff.',
    vpip: 0.48,
    pfr: 0.06,
    af: 0.8,
    cbet: 0.22,
    foldToCbet: 0.18,
    bluffFreq: 0.04,
    threeBetFreq: 0.02,
    foldTo3bet: 0.30,
    btnMultiplier: 1.1,
    coMultiplier: 1.05,
    hjMultiplier: 1.0,
    betSizingMean: 0.50,
    betSizingStd: 0.10,
    timingMeanMs: 1500,
    timingStdMs: 400,
  },
  maniac: {
    id: 'maniac',
    name: 'The Maniac',
    description: 'Extremely aggressive. Bets and raises with almost any two cards. Unpredictable.',
    vpip: 0.65,
    pfr: 0.55,
    af: 5.0,
    cbet: 0.92,
    foldToCbet: 0.15,
    bluffFreq: 0.45,
    threeBetFreq: 0.25,
    foldTo3bet: 0.25,
    btnMultiplier: 2.0,
    coMultiplier: 1.8,
    hjMultiplier: 1.5,
    betSizingMean: 0.90,
    betSizingStd: 0.25,
    timingMeanMs: 600,
    timingStdMs: 200,
  },
}

export const ARCHETYPE_ORDER: ArchetypeId[] = ['nit', 'tag', 'lag', 'callingstation', 'maniac']

// Default table composition for 6-max (5 AI opponents)
export const DEFAULT_TABLE_ARCHETYPES: ArchetypeId[] = [
  'tag',
  'callingstation',
  'lag',
  'nit',
  'maniac',
]

export const AI_NAMES: Record<ArchetypeId, string[]> = {
  nit: ['Frank', 'Walter', 'Harold', 'Raymond', 'Eugene'],
  tag: ['Alex', 'Jordan', 'Taylor', 'Morgan', 'Riley'],
  lag: ['Vince', 'Marco', 'Daria', 'Sasha', 'Leo'],
  callingstation: ['Phil', 'Barry', 'Donna', 'Carl', 'Gus'],
  maniac: ['Ace', 'Blaze', 'Ricky', 'Crash', 'Dice'],
}
